### ISSUE TITLE
Problem with routing

### ISSUE THREAD

**Issue by georgek146** [truffle-box/truffle-box-uport#6]
Just by running this out of the box, the uport login seems to work. However the problem comes with trying to access any of the other page routes like /dashboard or /profile. They all seem to redirect to "http://localhost:3000/?redirect=%2Fdashboard" and all you can view is the homepage again. Once I login through uport in the console I get this error: `Unhandled rejection Error: Failed to get value   uportlib.js:59140`

I'm wondering if this has to do with the new library connect that uport uses, or is this somehow related to how proptypes is handled?

**Comment by DiscRisknBisque** [comment]
@georgek146 You're correct the uPort library name changed. It's since been updated but please re-open if you see this same issue!
