### ISSUE TITLE
Test suite failed to run

### ISSUE THREAD

**Issue by m888m** [truffle-box/truffle-box-uport#7]
I got the following issue (likely a noob one ;)

```
 FAIL  src/App.test.js
  Test suite failed to run

    ENOENT: no such file or directory, stat '/home/m/dmc/truffle-box-uport/\config\polyfills.js'
        at Error (native)
      
      at Object.fs.statSync (fs.js:987:18)
      at Object.statSync (node_modules/graceful-fs/polyfills.js:297:22)


Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.007s
Ran all test suites.
```

at the same time, `truffle test` works just fine.
What am I doing wrong? Thanks for the heads-up.

**Comment by DiscRisknBisque** [comment]
@m888m No worries it was our issue! If you get the latest box you should be good to go. If you've already started and project with this box you can upgrade Jest to 18.1.0 and replace the "jest" part of package.json with what's in the the latest master.

Going to close this for now, but please re-open if needed!
